name: Deploy Application

on:
  push:
    branches:
      - main:

jobs:
  -create-deployment-artifact:
    name: Create Deployment Artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Compile CSS and javascript
        run: |
          npm install
          npm run production
