name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  create-deployment-artifact:
    name: Create Deployment Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile CSS and javascript
        run: |
          npm install
        #  npm run prod

      - name: Configure PHP 8.1
        uses: shivammathur/setup-php@main
        with:
          php-version: 8.1
          extensions: intl, zip, gd, pdo, pdo_mysql, opcache, bcmath, soap, sockets, exif, pcntl, imagick, redis, memcached, apcu, xdebug, xml, mbstring, ctype, fileinfo, json, openssl, bcmath, tokenizer
          coverage: none
      - name : Install Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          mv composer.phar /usr/local/bin/composer
          composer install --no-dev --optimize-autoloader --no-interaction --no-progress --no-suggest --prefer-dist
